// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base-common/base-button.vue')['default']
    BaseInputConfirm: typeof import('./src/components/base-common/base-input-confirm.vue')['default']
    BaseInputDate: typeof import('./src/components/base-common/base-input-date.vue')['default']
    BaseInputNumber: typeof import('./src/components/base-common/base-input-number.vue')['default']
    BaseInputPassword: typeof import('./src/components/base-common/base-input-password.vue')['default']
    BaseInputSelect: typeof import('./src/components/base-common/base-input-select.vue')['default']
    BaseInputText: typeof import('./src/components/base-common/base-input-text.vue')['default']
    BaseLabel: typeof import('./src/components/base-common/base-label.vue')['default']
    BaseLink: typeof import('./src/components/base-common/base-link.vue')['default']
    BaseNoItem: typeof import('./src/components/base-common/base-no-item.vue')['default']
    BaseTextarea: typeof import('./src/components/base-common/base-textarea.vue')['default']
    ButtonToast: typeof import('./src/components/component-common/button-toast.vue')['default']
    Dialog: typeof import('./src/components/component-common/Dialog.vue')['default']
    DialogCommon: typeof import('./src/components/dialog/dialog-common.vue')['default']
    GuestView: typeof import('./src/components/guestView/index.vue')['default']
    Language: typeof import('./src/components/language.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Loading: typeof import('./src/components/loading/index.vue')['default']
    LoadingComponent: typeof import('./src/components/loading/loading-component.vue')['default']
    Notification: typeof import('./src/components/notification/index.vue')['default']
    Offline: typeof import('./src/components/no-internet/Offline.vue')['default']
    Otp: typeof import('./src/components/auth/otp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlotDialog: typeof import('./src/components/dialog/slot-dialog.vue')['default']
    Toast: typeof import('./src/components/toast/index.vue')['default']
  }
}

export {}
